### ISSUE TITLE
Can we avoid depending on Rffsa as we only use one function from it?

### ISSUE THREAD

**Issue by andrew-edwards** [pbs-assess/pacea#22]
And it depends on quite a few other packages (I had to install 10 new ones I'd never heard of). 
I noticed it looks like only one function is used, so can we just copy that and reference it appropriately to the original package? Will help avoid some random build fail in the future because some dependent package changed.

**Comment by travistai2** [comment]
Yes for sure. Sorry about that, I agree that the package is unnecessary. I didn't check how many new ones were needed. Also after our discussion about creating the data repository, I realized a few things would have to be changed:
1. using `saveRDS` instead of `use_data` as we're no longer saving these data to a package.
2. the `Rffsa::load_github_data` is specific for saved data using `use_data`. It doesn't seem to work with data that wasn't saved that way. 

So we should be able to just save data to the pacea-data repository and load it with `get_pacea_data` without dependencies.

**Comment by andrew-edwards** [comment]
Yes, that function works. Awesome.
